Repository liftedinit/many-rs, pull requests merged in 2022-08, with the labels that each got.

#177 Fix attribute errors being created as unknown
  src/many-error/src/error.rs
  src/many-modules/src/_4_events.rs
Labels: bug

#173 Mock server
  Cargo.lock
  Cargo.toml
  src/many-mock/Cargo.toml
  src/many-mock/src/lib.rs
  src/many-mock/src/server.rs
  src/many-mock/tests/features/integration.feature
  src/many-mock/tests/integration.rs
  src/many-mock/tests/testmockfile.toml
  src/many/Cargo.toml
  src/many/src/main.rs
Labels: enhancement

#78 AbciBackend module unit tests - `mockall`
  Cargo.lock
  src/many-modules/src/_1000_abci_backend.rs
Labels: enhancement

#187 Set CircleCI resource class
  .circleci/config.yml
Labels: enhancement, ci

#191 Fix cargo install with the repo directly
  .circleci/config.yml
  Cargo.lock
  src/many-server/src/server.rs
  src/many/src/main.rs
Labels: bug
