Repository liftedinit/many-rs, pull requests merged in 2022-11, with the labels that each got.

#214 Migration framework
  Cargo.Bazel.lock
  Cargo.lock
  Cargo.toml
  WORKSPACE.bazel
  cargo-bazel-lock.json
  rust-toolchain.toml
  src/many-client/src/client.rs
  src/many-error/src/error.rs
  src/many-error/src/reason/minicbor.rs
  src/many-identity-dsa/src/impls/ecdsa.rs
  src/many-identity-dsa/src/impls/ed25519.rs
  src/many-identity-hsm/src/lib.rs
  src/many-identity/src/address.rs
  src/many-macros/src/lib.rs
  src/many-migration/BUILD.bazel
  src/many-migration/Cargo.toml
  src/many-migration/src/lib.rs
  src/many-migration/tests/migrations.rs
  src/many-mock/src/lib.rs
  src/many-mock/src/server.rs
  src/many-modules/src/_0_base.rs
  src/many-modules/src/_4_events.rs
  src/many-modules/src/_9_account.rs
  src/many-protocol/src/request.rs
  src/many-protocol/src/response.rs
  src/many-types/src/attributes.rs
  src/many-types/src/cbor.rs
  src/many-types/src/either.rs
  src/many/src/main.rs
Labels: enhancement

#215 AttributeRelatedIndex functions should be const
  src/many-types/src/lib.rs
Labels: refactor

#221 Update rules_rust and Rust nightly
  Cargo.Bazel.lock
  WORKSPACE.bazel
  cargo-bazel-lock.json
Labels: enhancement

#222 Fix response message address
  src/many-mock/src/server.rs
Labels: bug

#201 Update Memo structure to latest specification
  Cargo.Bazel.lock
  Cargo.lock
  cargo-bazel-lock.json
  src/many-error/BUILD.bazel
  src/many-migration/BUILD.bazel
  src/many-migration/Cargo.toml
  src/many-migration/README.md
  src/many-migration/src/lib.rs
  src/many-migration/tests/migrations.rs
  src/many-modules/Cargo.toml
  src/many-modules/src/_4_events.rs
  src/many-modules/src/_4_events/list.rs
  src/many-modules/src/_9_account/features/multisig.rs
  src/many-types/Cargo.toml
  src/many-types/src/cbor.rs
  src/many-types/src/lib.rs
  src/many-types/src/memo.rs
  src/many-types/src/memo/legacy.rs
Labels: breaking change
