Repository liftedinit/many-rs, pull requests merged in 2022-06, with the labels that each got.

#101 Refactor `tests::identity()` & add missing derive
  src/many/src/server/module.rs
  src/many/src/server/module/_1002_idstore.rs
  src/many/src/server/module/_1002_idstore/get.rs
  src/many/src/server/module/_2_ledger.rs
  src/many/src/server/module/_3_kvstore.rs
  src/many/src/server/module/_9_account.rs
  src/many/src/types/identity.rs
Labels: enhancement

#103 Add Debug to CreateReturn
  src/many/src/server/module/_9_account.rs
Labels: enhancement

#102 Fix lcov-reporter-action source
  .github/workflows/coverage.yml
Labels: enhancement

#104 Add --from-hex flag to send raw messages and wait for the response
  src/many-cli/src/main.rs
Labels: enhancement

#106 More Clone/Debug/PartialEq derives
  src/many/src/server/module/_9_account.rs
  src/many/src/server/module/_9_account/features/multisig.rs
  src/many/src/types/ledger.rs
Labels: enhancement

#111 Replace `String` with `Role`. Make Transaction `Debug`
  Cargo.lock
  src/many/src/types/ledger.rs
Labels: enhancement

#112 Use `ubuntu-22.04` instead of `ubuntu-latest` in CI
  .github/workflows/ci.yml
Labels: enhancement

#113 Add new specification fields and transaction type
  src/many/src/server/module/_9_account/features/multisig.rs
  src/many/src/types/identity.rs
  src/many/src/types/ledger.rs
Labels: alpha

#114 Add multisig info state
  Cargo.lock
  src/many/src/server/module/_9_account/features/multisig.rs
Labels: enhancement

#117 Limit the size of memo and data for multisig tx
  src/many/src/server/module/_9_account/features/multisig.rs
Labels: enhancement

#118 Update to `cbor-diag` 0.1.9
  Cargo.lock
  src/many-cli/Cargo.toml
  src/many/Cargo.toml
Labels: bug

#120 Allow accounts to be disabled with a reason
  Cargo.lock
  src/many/src/message/error.rs
  src/many/src/server/module/_9_account.rs
  src/many/src/types.rs
Labels: enhancement

#121 Return the first role instead of the last one
  src/many/src/server/module/_9_account.rs
Labels: enhancement

#122 Remove pub on fields and add API endpoints
  src/many/src/message/error.rs
Labels: enhancement

#123 More QoL by reusing the either crate
  src/many/src/types.rs
  src/many/src/types/either.rs
Labels: enhancement

#125 Rename delete to disable WRT accounts
  src/many/src/server/module/_9_account.rs
  src/many/src/server/module/_9_account/features/multisig.rs
  src/many/src/types/ledger.rs
Labels: enhancement

#124 Rename LedgerTransactions to Events
  Cargo.lock
  src/many/src/server/module.rs
  src/many/src/server/module/_4_events.rs
  src/many/src/server/module/_4_events/info.rs
  src/many/src/server/module/_4_events/list.rs
  src/many/src/server/module/_4_ledger_transactions.rs
  src/many/src/server/module/_4_ledger_transactions/info.rs
  src/many/src/server/module/_9_account/features/multisig.rs
  src/many/src/types.rs
  src/many/src/types/either.rs
  src/many/src/types/events.rs
  src/many/src/types/ledger.rs
Labels: enhancement

#128 Ignore hsm tests in normal cargo test
  src/many/Cargo.toml
  src/many/src/hsm.rs
Labels: enhancement

#129 Remove unused simple http server code from transport
  src/many/src/transport.rs
  src/many/src/transport/http.rs
Labels: enhancement

#130 Add strum macros to EventKind and QoL on Role
  Cargo.lock
  src/many/src/server/module/_9_account.rs
  src/many/src/types/events.rs
Labels: enhancement

#133 `webauthn` flag in Protected Header
  src/many-macros/src/lib.rs
  src/many/src/message.rs
Labels: enhancement

#74 KvStoreCommands module unit tests - `mockall`
  Cargo.lock
  src/many/src/server/module/_7_kvstore_commands.rs
  src/many/src/server/module/_7_kvstore_commands/delete.rs
  src/many/src/server/module/_7_kvstore_commands/put.rs
Labels: enhancement

#144 Automatic execution should not be listed on anonymous filter
  src/many/src/types/events.rs
Labels: bug
