Repository liftedinit/many-rs, pull requests merged in 2023-06, with the labels that each got.

#370 fix: add a cache to prevent duplicated messages
  .circleci/config.yml
  Cargo.Bazel.lock
  Cargo.lock
  Cargo.toml
  WORKSPACE.bazel
  cargo-bazel-lock.json
  docker/docker-compose-kvstore.jsonnet
  docker/docker-compose-ledger.jsonnet
  docker/update_config.sh
  scripts/run.sh
  src/many-abci/BUILD.bazel
  src/many-abci/Cargo.toml
  src/many-abci/src/abci_app.rs
  src/many-abci/src/main.rs
  src/many-client-macros/src/lib.rs
  src/many-client/BUILD.bazel
  src/many-client/Cargo.toml
  src/many-client/src/client.rs
  src/many-client/src/client/base.rs
  src/many-client/src/client/blockchain.rs
  src/many-client/src/client/blocking.rs
  src/many-client/src/client/ledger.rs
  src/many-error/src/error.rs
  src/many-kvstore/BUILD.bazel
  src/many-kvstore/Cargo.toml
  src/many-kvstore/src/main.rs
  src/many-ledger/BUILD.bazel
  src/many-ledger/Cargo.toml
  src/many-ledger/src/main.rs
  src/many-protocol/BUILD.bazel
  src/many-server-cache/BUILD.bazel
  src/many-server-cache/Cargo.toml
  src/many-server-cache/src/lib.rs
  src/many-server/BUILD.bazel
  src/many-server/Cargo.toml
  src/many-server/src/lib.rs
  src/many-server/src/server.rs
  src/many-server/src/validator.rs
  tests/e2e/kvstore/cache.bats
  tests/e2e/ledger/cache.bats
  tests/resiliency/ledger/tendermint.bats
  tests/test_helper/kvstore.bash
  tests/test_helper/ledger.bash
Labels: bug

#385 fix: release trigger pattern
  .circleci/config.yml
Labels: ci

#381 feat: update maximum key/value length
  Cargo.Bazel.lock
  Cargo.lock
  cargo-bazel-lock.json
  src/many-kvstore/Cargo.toml
  src/many-kvstore/src/module.rs
  src/many-kvstore/src/module/account.rs
  src/many-modules/src/_7_kvstore_commands/put.rs
  tests/e2e/kvstore/kvstore.bats
  tests/resiliency/kvstore/limits.bats
  tests/test_helper/kvstore.bash
Labels: enhancement

#379 chore: update dependencies
  Cargo.Bazel.lock
  Cargo.lock
  Cargo.toml
  cargo-bazel-lock.json
  src/http_proxy/Cargo.toml
  src/idstore-export/Cargo.toml
  src/kvstore/Cargo.toml
  src/ledger-db/Cargo.toml
  src/ledger/Cargo.toml
  src/ledger/src/main.rs
  src/many-abci/Cargo.toml
  src/many-cli-helpers/Cargo.toml
  src/many-client-macros/Cargo.toml
  src/many-client/Cargo.toml
  src/many-error/Cargo.toml
  src/many-identity-dsa/Cargo.toml
  src/many-identity-hsm/Cargo.toml
  src/many-identity-webauthn/Cargo.toml
  src/many-identity/Cargo.toml
  src/many-kvstore/Cargo.toml
  src/many-ledger/Cargo.toml
  src/many-ledger/test-macros/Cargo.toml
  src/many-ledger/test-utils/Cargo.toml
  src/many-macros/Cargo.toml
  src/many-migration/Cargo.toml
  src/many-mock/Cargo.toml
  src/many-modules/Cargo.toml
  src/many-protocol/Cargo.toml
  src/many-server/Cargo.toml
  src/many-types/Cargo.toml
  src/many/Cargo.toml
Labels: enhancement

#383 feat: kvstore.list
  src/kvstore/src/main.rs
  src/many-kvstore/src/module.rs
  src/many-kvstore/src/storage.rs
  src/many-kvstore/src/storage/iterator.rs
  src/many-kvstore/tests/common/mod.rs
  src/many-kvstore/tests/kvstore.rs
  src/many-modules/src/_3_kvstore.rs
  src/many-modules/src/_3_kvstore/list.rs
  src/many-types/src/lib.rs
  tests/e2e/kvstore/kvstore.bats
Labels: enhancement

#216 Data module should serialize to maps and proper tagged types
  Cargo.Bazel.lock
  Cargo.lock
  cargo-bazel-lock.json
  src/many-ledger/src/migration/data.rs
  src/many-modules/Cargo.toml
  src/many-modules/src/_5_data.rs
  src/many-modules/src/_5_data/get_info.rs
  src/many-modules/src/_5_data/info.rs
  src/many-modules/src/_5_data/query.rs
  src/many-modules/src/_5_data/types.rs
  src/many-modules/src/lib.rs
  src/many-types/src/cbor.rs
  src/many-types/src/lib.rs
  tests/resiliency/ledger/account_count_migration.bats
Labels: bug

#388 fix: don't list disabled keys
  src/many-kvstore/src/storage.rs
  src/many-kvstore/tests/kvstore.rs
  tests/e2e/kvstore/kvstore.bats
Labels: bug

#389 fix: add kvstore.list to endpoints
  src/many-kvstore/src/module.rs
Labels: bug
